"""Standalone 2-D Poisson-Boltzmann (Gouy-Chapman) two-facet stripe model.

GENERATED by the TEMPLATE pipeline (template gc_polyc_pb2d v1) — do not edit by hand.
Problem: p02_bistable_conc
Physics frozen per templates/gc_polyc/physics.frozen.md; only the FILLED
PARAMETERS block below was produced from the problem statement. Pure
numpy/scipy; no external project imports.

Validated against the reference Gouy-Chapman solver.
"""

import json

import numpy as np
from scipy.optimize import brentq, OptimizeResult
from scipy.sparse import coo_matrix
from scipy.sparse.linalg import spsolve

# ── physical constants (SI; frozen) ──────────────────────────────────
EPS0 = 8.8541878128e-12     # F/m
F = 96485.33212             # C/mol
R = 8.31446261815324        # J/(mol K)
T = 298.15                  # K
EPS_R = 78.5                # water, article SI Table S1

# ═════════════════════════════════════════════════════════════════════
# FILLED PARAMETERS — the only generated content in this file
# ═════════════════════════════════════════════════════════════════════
CASE = {
    'E_M':   0.15,                       # V vs SHE
    'E_pzc': [0.3, -0.3],  # V vs SHE (facet 1, facet 2)
    'C_H':   [0.5, 0.5],      # F/m^2
    'x':     0.5,                         # facet-1 fraction
    'c_b':   10.0,                       # mol/m^3 (1 mM = 1.0)
    'L':     1e-07,                         # m
}
MESH = {'Ny': 8, 'Nz': 64, 'Z_max_factor': 8.0}                    # tier 'diagnostic'
SWEEP = {
    'var': "E_M",          # 'E_M' or 'none'
    'lo': -0.5, 'hi': 0.5, 'n': 41,
    'panel_L_nm': [100.0],
}
# ═════════════════════════════════════════════════════════════════════

# ── frozen model code (port of GC-polyc gc_pb_2d.py, sparse path) ────


def make_z_mesh(Nz, Z_max, alpha=3.0):
    """tanh-stretched z mesh on [0, Z_max], refined at z=0; shape (Nz+1,)."""
    i = np.arange(Nz + 1, dtype=float)
    return Z_max * (1.0 - np.tanh(alpha * (Nz - i) / Nz) / np.tanh(alpha))


def sigma_GC(psi_0, c_b, eps_r=EPS_R, temp=T):
    """Chapman-Grahame diffuse-layer charge [C/m^2]."""
    return np.sqrt(8.0 * EPS0 * eps_r * R * temp * c_b) * np.sinh(
        F * psi_0 / (2.0 * R * temp))


def solve_psi0(E_M, E_pzc, C_H, c_b, eps_r=EPS_R, temp=T):
    """Solve sigma_GC(psi_0) = C_H (E_M - E_pzc - psi_0) for psi_0 [V]."""
    def f(psi):
        return sigma_GC(psi, c_b, eps_r, temp) - C_H * (E_M - E_pzc - psi)
    return brentq(f, -3.0, 3.0, xtol=1e-12, rtol=1e-12)


def residual_2d(phi_flat, p):
    """Dimensionless 2-D PB residual, shape (Ny*Nz,). Pure numpy."""
    Ny, Nz = p['Ny'], p['Nz']
    zeta, deta, nu, Phi = p['zeta'], p['deta'], p['nu'], p['Phi']

    phi = phi_flat.reshape(Ny, Nz)
    phi_aug = np.concatenate([phi, np.zeros((Ny, 1))], axis=1)  # Dirichlet k=Nz

    # Robin BC at k=0, second-order one-sided stencil
    h0 = zeta[1] - zeta[0]
    h1 = zeta[2] - zeta[1]
    cn = h0 + h1
    dphi_dz_0 = (cn**2 * phi_aug[:, 1] - h0**2 * phi_aug[:, 2]
                 - h1 * (2.0 * h0 + h1) * phi_aug[:, 0]) / (h0 * h1 * cn)
    R_bc = dphi_dz_0 - nu * (phi_aug[:, 0] - Phi)

    # Interior 5-point PB at k=1..Nz-1
    h_m = zeta[1:-1] - zeta[:-2]
    h_p = zeta[2:] - zeta[1:-1]
    phi_c = phi_aug[:, 1:-1]
    d2z = (2.0 / (h_m + h_p)) * ((phi_aug[:, 2:] - phi_c) / h_p
                                 - (phi_c - phi_aug[:, :-2]) / h_m)
    d2y = (np.roll(phi_c, -1, axis=0) - 2.0 * phi_c
           + np.roll(phi_c, 1, axis=0)) / (p['deta'] * p['deta'])
    R_int = d2z + d2y - np.sinh(phi_c)

    return np.concatenate([R_bc[:, None], R_int], axis=1).ravel()


def build_jac_csr(phi_flat, p):
    """Analytical sparse CSR Jacobian of residual_2d (<=5 nnz/row)."""
    Ny, Nz = int(p['Ny']), int(p['Nz'])
    zeta, deta, nu = p['zeta'], float(p['deta']), p['nu']

    phi = phi_flat.reshape(Ny, Nz)
    inv_deta2 = 1.0 / (deta * deta)
    h0 = zeta[1] - zeta[0]
    h1 = zeta[2] - zeta[1]
    cn = h0 + h1
    h_m = zeta[1:-1] - zeta[:-2]
    h_p = zeta[2:] - zeta[1:-1]
    inv_hm, inv_hp = 1.0 / h_m, 1.0 / h_p
    c2 = 2.0 / (h_m + h_p)

    max_nnz = 3 * Ny + 5 * Ny * (Nz - 1)
    rows = np.empty(max_nnz, dtype=np.int32)
    cols = np.empty(max_nnz, dtype=np.int32)
    data = np.empty(max_nnz, dtype=np.float64)
    ptr = 0

    dbc0 = -h1 * (2 * h0 + h1) / (h0 * h1 * cn) - nu
    dbc1 = cn / (h0 * h1)
    dbc2 = -h0 / (h1 * cn)
    for i in range(Ny):
        r = i * Nz
        rows[ptr] = r; cols[ptr] = r;     data[ptr] = dbc0[i]; ptr += 1
        rows[ptr] = r; cols[ptr] = r + 1; data[ptr] = dbc1;    ptr += 1
        rows[ptr] = r; cols[ptr] = r + 2; data[ptr] = dbc2;    ptr += 1

    for i in range(Ny):
        il, ir = (i - 1) % Ny, (i + 1) % Ny
        for j in range(Nz - 1):
            k = j + 1
            r = i * Nz + k
            ctr = c2[j] * (-inv_hp[j] - inv_hm[j]) - 2 * inv_deta2 - np.cosh(phi[i, k])
            rows[ptr] = r; cols[ptr] = r;             data[ptr] = ctr; ptr += 1
            rows[ptr] = r; cols[ptr] = r - 1;         data[ptr] = c2[j] * inv_hm[j]; ptr += 1
            if k < Nz - 1:
                rows[ptr] = r; cols[ptr] = r + 1;     data[ptr] = c2[j] * inv_hp[j]; ptr += 1
            rows[ptr] = r; cols[ptr] = il * Nz + k;   data[ptr] = inv_deta2; ptr += 1
            rows[ptr] = r; cols[ptr] = ir * Nz + k;   data[ptr] = inv_deta2; ptr += 1

    N = Ny * Nz
    return coo_matrix((data[:ptr], (rows[:ptr], cols[:ptr])), shape=(N, N)).tocsr()


def solve_pb_2d(case, mesh):
    """Damped sparse-Newton solve. Returns (phi_yz, sigma_M, sigma_bar, result)."""
    E_M = float(case['E_M'])
    E_pzc = np.asarray(case['E_pzc'], dtype=float)
    C_H = np.asarray(case['C_H'], dtype=float)
    x = float(case['x'])
    c_b = float(case['c_b'])
    L = float(case['L'])
    Ny, Nz = int(mesh['Ny']), int(mesh['Nz'])
    Z_max_factor = float(mesh.get('Z_max_factor', 8.0))

    lambda_D = np.sqrt(EPS0 * EPS_R * R * T / (2.0 * F**2 * c_b))
    Z_max = Z_max_factor * lambda_D
    y = np.linspace(0.0, L, Ny, endpoint=False)
    z = make_z_mesh(Nz, Z_max, alpha=3.0)

    zeta = z / lambda_D
    deta = (L / Ny) / lambda_D
    facet = np.where(y < x * L, 0, 1)
    nu = C_H[facet] * lambda_D / (EPS0 * EPS_R)
    Phi = F * (E_M - E_pzc[facet]) / (R * T)
    p = {'Ny': Ny, 'Nz': Nz, 'zeta': zeta, 'deta': deta, 'nu': nu, 'Phi': Phi}

    # Initial guess: analytical GC profile per y-strip
    phi_init = np.zeros((Ny, Nz))
    for i in range(Ny):
        try:
            psi_0_i = solve_psi0(E_M, E_pzc[facet[i]], C_H[facet[i]], c_b)
        except Exception:
            psi_0_i = 0.0
        phi0_i = F * psi_0_i / (R * T)
        gamma_i = np.tanh(phi0_i / 4.0)
        arg = np.clip(gamma_i * np.exp(-zeta[:Nz]), -1.0 + 1e-12, 1.0 - 1e-12)
        phi_init[i, :] = 4.0 * np.arctanh(arg)

    # Damped Newton with sparse analytical Jacobian (port of GC 'sparse' path)
    x_s = phi_init.ravel().copy()
    f_s = residual_2d(x_s, p)
    converged = False
    fn_prev = float('inf')
    stag = 0
    for _ in range(50):
        fn = float(np.linalg.norm(f_s))
        if fn < 1e-8:
            converged = True
            break
        if fn_prev > 0 and abs(fn - fn_prev) / fn_prev < 1e-3:
            stag += 1
            if stag >= 3:
                break
        else:
            stag = 0
        fn_prev = fn
        J = build_jac_csr(x_s, p)
        dx = spsolve(J, -f_s)
        alpha = 1.0
        fn2 = fn * fn
        f_try = f_s
        for __ in range(30):
            f_try = residual_2d(x_s + alpha * dx, p)
            if float(np.dot(f_try, f_try)) < fn2 * (1.0 - 1e-4 * alpha):
                break
            alpha *= 0.5
        x_s = x_s + alpha * dx
        f_s = f_try
    fn_final = float(np.linalg.norm(f_s))
    success = converged or (fn_final < 1e-6)
    result = OptimizeResult(x=x_s, fun=f_s, success=success,
                            message='Converged' if success else 'Max iterations reached')

    phi_d_full = np.concatenate([result.x.reshape(Ny, Nz), np.zeros((Ny, 1))], axis=1)
    phi_yz = phi_d_full * (R * T / F)
    psi_surf = phi_yz[:, 0]
    sigma_M = C_H[facet] * (E_M - E_pzc[facet] - psi_surf)
    sigma_bar = float(np.mean(sigma_M))
    return phi_yz, sigma_M, sigma_bar, result


def main():
    # Single solve at CASE values (always; gates parse RESULT_JSON)
    phi_yz, sigma_M, sigma_bar, result = solve_pb_2d(CASE, MESH)
    out = {
        'success': bool(result.success),
        'residual_norm': float(np.linalg.norm(result.fun)),
        'sigma_bar_C_per_m2': sigma_bar,
        'psi_surf_min_V': float(phi_yz[:, 0].min()),
        'psi_surf_max_V': float(phi_yz[:, 0].max()),
        'case': {k: (list(v) if isinstance(v, list) else v) for k, v in CASE.items()},
        'mesh': MESH,
    }

    # Optional E_M sweep -> one CSV per requested L
    if SWEEP['var'] == 'E_M' and SWEEP['n'] >= 2:
        E_vals = np.linspace(SWEEP['lo'], SWEEP['hi'], SWEEP['n'])
        sweep_ok = True
        for L_nm in SWEEP['panel_L_nm']:
            case_L = dict(CASE)
            case_L['L'] = float(L_nm) * 1e-9
            sig = []
            for E in E_vals:
                c = dict(case_L)
                c['E_M'] = float(E)
                _, _, sb, res = solve_pb_2d(c, MESH)
                sig.append(sb)
                sweep_ok = sweep_ok and bool(res.success) \
                    and float(np.linalg.norm(res.fun)) < 1e-6
            sig = np.array(sig)
            C_dl = np.gradient(sig, E_vals)
            fname = f'sweep_L{round(float(L_nm))}nm.csv'
            np.savetxt(fname, np.column_stack([E_vals, sig, C_dl]),
                       header='E_M_V,sigma_bar_Cm2,C_dl_Fm2',
                       delimiter=',', comments='')
            out.setdefault('sweep_csv', []).append(fname)
        out['sweep_all_converged'] = bool(sweep_ok)
        out['C_dl_min_F_per_m2'] = float(np.min(C_dl))

    print('RESULT_JSON: ' + json.dumps(out))


if __name__ == '__main__':
    main()
