"""Standalone 2-D two-facet modified Poisson-Boltzmann (polycrystalline EDL) model.

GENERATED by the TEMPLATE pipeline (template polyc_mpb2d v1) — do not edit by hand.
Problem: p12_booth_single
Physics frozen per templates/polyc_mpb2d/physics.frozen.md; only the FILLED
PARAMETERS block below was produced from the problem statement. Pure
numpy/scipy; no external project imports.

Faithful inline port of the reference modified-Poisson-Boltzmann solver
(constants → physics → pb1d → pb2d → analytics, eqs 1-13). The emitted skeleton
reproduces the reference solutions to machine precision (the solver is inlined).
Erratum fixes carried from the reference: E1 (n_w D₄≡D), E2 (Robin BC default
bc='eps_S'), E4 (c_b^(A-) = 1/c_b[M]).
"""

import json

import numpy as np
import scipy.sparse as sp
from scipy.interpolate import CubicSpline
from scipy.optimize import root
from scipy.optimize._numdiff import approx_derivative
from scipy.signal import find_peaks
from scipy.sparse.linalg import spsolve

# ═════════════════════════════════════════════════════════════════════
# FILLED PARAMETERS — the only generated content in this file
# ═════════════════════════════════════════════════════════════════════
CASE = {
    'E_M':    -0.15,                       # V vs SHE
    'E_pzc':  [0.0, 0.0],  # V vs SHE (facet 1, facet 2)
    'C_H':    [0.25, 0.25],      # F/m^2 (Helmholtz, per facet)
    'x':      0.5,                         # facet-1 fraction
    'c_b':    0.1,                       # mol/m^3 (1 mM = 1.0)
    'L':      1e-08,                         # m
}
ADS = {
    'E_ads0':    0.45,                 # V (adsorption reference potential)
    'theta_max': 0.0,              # 0.0 => adsorption OFF
}
MESH = {'Ny': 24, 'Nz': 48, 'stretch': 7, 'z_max_over_lamD': 25, 'bc': 'eps_S'}                     # tier 'diagnostic' (carries Ny, Nz, stretch, z_max_over_lamD, bc)
SWEEP = {
    'var': "none",           # 'E_M' or 'none'
    'lo': -0.5, 'hi': 0.5, 'n': 41,
    'panel_L_nm': [10.0],
}
# c_b UNIT CONVERSION (binding): the template slot c_b is in mol/m^3 (1 mM = 1.0),
# but every polyc solver helper (lambda_D, n_b, v_frac, C_ads's c_b_Aminus) takes
# concentration in mol/L (M). 1 mol/m^3 = 1e-3 mol/L. Convert ONCE here and route
# ALL solver calls through c_b_M.  c_b_M == mM_to_M(c_b) since the slot value
# numerically equals the mM figure.
C_B_M = CASE['c_b'] * 1e-3                      # mol/L (M) — feed this to the solver
# ═════════════════════════════════════════════════════════════════════

# ═════════════════════════════════════════════════════════════════════
# FROZEN SOLVER — faithful inline port of polyc/model/src (do not edit).
# Intra-package imports stripped; C.* / PH.* / pb1d.* prefixes rewritten to
# bare module-global names. Numerics byte-identical to the polyc reference.
# ═════════════════════════════════════════════════════════════════════

# ── constants.py (Table-S1 SI; CONSTRAINTS §1) ───────────────────────
import math

# ----- General physical constants (Table S1) -----
k_B   = 1.381e-23      # J/K
T     = 298.0          # K
e_0   = 1.6021e-19     # C
N_A   = 6.02e23        # 1/mol
eps_0 = 8.85e-12       # F/m
c_w   = 55.6           # M  (pure-water molarity)

# ----- Electrolyte (Table S1) -----
eps_opt = 1.8  * eps_0   # F/m  optical permittivity (SI ref 4)
eps_HP  = 30.0 * eps_0   # F/m  metal<->HP gap; enters only via C_H = eps_HP/l_HP (SI ref 5)
eps_S   = 78.5 * eps_0   # F/m  bulk-solution permittivity (bulk water)
d_t     = 3.1e-10        # m    lattice size = (c_w N_A)^(-1/3); table-rounded 3.1 Angstrom
gamma_p = 3.0            # ion-size factor gamma_+  = (d_+/d_t)^3
gamma_m = 3.0            # ion-size factor gamma_-
p_dip   = 1.58e-29       # C*m  solvent dipole moment (pinned; see p_from_table)

# ----- Electrode (Table S1) -----
L_default = 10e-9        # m     unit-cell length (swept 1-100 nm)
x_default = 0.5          # facet-1 fraction
E_pzc_111 = +0.3         # V_SHE  111 / "T" facet (SI refs 3,6)
E_pzc_110 = -0.1         # V_SHE  110 / "S" facet (SI ref 7)
N_tot     = 1.5029e19    # 1/m^2  = 4/(sqrt3 a_Pt^2), a_Pt = 3.92 Angstrom

# ----- Adsorption (Table S1) -----
E_ads0_default    = 0.45  # V
theta_max_default = 0.01  # fraction (1%)

# ----- article-facing defaults (per-figure overrides live in CONSTRAINTS §3) -----
C_H_default_uFcm2 = 50.0  # uF/cm^2 (Fig S3 uses 25)
c_b_default_mM    = 0.1   # mM


# ----- unit conversions -----
def uFcm2_to_SI(c):   # uF/cm^2 -> F/m^2  (1 uF/cm^2 = 1e-2 F/m^2)
    return c * 1e-2


def SI_to_uFcm2(c):   # F/m^2 -> uF/cm^2
    return c * 1e2


def mM_to_M(c):       # mM -> mol/L (M)
    return c * 1e-3


C_H_default = uFcm2_to_SI(C_H_default_uFcm2)   # 0.5 F/m^2
c_b_default = mM_to_M(c_b_default_mM)          # 1e-4 M

# ----- derived quantities (CONSTRAINTS §1 "Derived" block) -----
beta = 1.0 / (k_B * T)            # 1/J ; ~2.430e20

n_w_b      = 1.0 / d_t**3          # 1/m^3 ; ~3.357e28  (canonical)
n_w_b_conc = c_w * 1e3 * N_A       # 1/m^3 ; ~3.347e28  (concentration form)


def n_b(c_b_M):
    """Bulk ion number density [1/m^3] for bulk conc c_b in mol/L (M)."""
    return c_b_M * 1e3 * N_A


# Inlining alias: polyc accessed this as C.n_b(...), which never clashed with the
# LOCAL value variable `n_b` inside solve_dirichlet/solve_robin/solve_2d. After
# stripping the C. prefix, those functions assign `n_b` locally, so they must call
# the module function under a distinct name to avoid UnboundLocalError. Identical
# numerics — n_b_local IS the module n_b.
n_b_local = n_b


def v_frac(c_b_M):
    """Bulk volume fraction of solvated ions, v = 2 d_t^3 n_b (eq-2 D term)."""
    return 2.0 * d_t**3 * n_b(c_b_M)


def lambda_D(c_b_M):
    """Debye length [m], monovalent: sqrt(eps_S k_B T / (2 e_0^2 n_b))."""
    return math.sqrt(eps_S * k_B * T / (2.0 * e_0**2 * n_b(c_b_M)))


def p_from_table():
    """Re-derive the solvent dipole p = sqrt(3 d_t^3 (eps_S - eps_opt) k_B T)
    (Table S1 definition; should equal p_dip to table rounding)."""
    return math.sqrt(3.0 * d_t**3 * (eps_S - eps_opt) * k_B * T)


# ── physics.py (CONSTRAINTS §2 eqs 2-4; modified-PB kernel) ───────────
# canonical solvent dipole (defining formula, full precision)
P_DIP = p_from_table()

# Overflow guard for the dimensionless exponent (see polyc physics.py rationale).
_EXP_CLAMP = 200.0


def _bphi(phi):
    return np.clip(beta * e_0 * np.asarray(phi, dtype=float), -_EXP_CLAMP, _EXP_CLAMP)


def sinhc(u):
    """sinh(u)/u, with a small-u series (-> 1 at u = 0)."""
    u = np.clip(np.asarray(u, dtype=float), -_EXP_CLAMP, _EXP_CLAMP)
    scalar = (u.ndim == 0)
    u = np.atleast_1d(u)
    out = np.empty_like(u)
    small = np.abs(u) < 1e-4
    us = u[small]
    out[small] = 1.0 + us**2 / 6.0 + us**4 / 120.0
    ub = u[~small]
    out[~small] = np.sinh(ub) / ub
    return float(out[0]) if scalar else out


def langevin_L(u):
    """Langevin function L(u) = coth(u) - 1/u, with small-u series (-> u/3)."""
    u = np.asarray(u, dtype=float)
    scalar = (u.ndim == 0)
    u = np.atleast_1d(u)
    out = np.empty_like(u)
    small = np.abs(u) < 1e-4
    us = u[small]
    out[small] = us / 3.0 - us**3 / 45.0
    ub = u[~small]
    out[~small] = 1.0 / np.tanh(ub) - 1.0 / ub
    return float(out[0]) if scalar else out


def langevin_Lc(u):
    """L(u)/u, smooth at u = 0 (-> 1/3). Used by eps_eff so the E -> 0 limit needs
    no division by the field."""
    u = np.asarray(u, dtype=float)
    scalar = (u.ndim == 0)
    u = np.atleast_1d(u)
    out = np.empty_like(u)
    small = np.abs(u) < 1e-3
    us = u[small]
    out[small] = 1.0 / 3.0 - us**2 / 45.0 + 2.0 * us**4 / 945.0
    ub = u[~small]
    out[~small] = (1.0 / np.tanh(ub) - 1.0 / ub) / ub
    return float(out[0]) if scalar else out


def denominator_D(phi, E, v):
    """eq 2 shared denominator D(phi, E):
        D = (v/2)(g+ e^{-b e0 phi} + g- e^{+b e0 phi})
            + [1 - (v/2)(g+ + g-)] * sinh(bpE)/(bpE).
    Note D(0,0) = 1 for any v."""
    bphi = _bphi(phi)
    S = sinhc(beta * P_DIP * np.asarray(E, dtype=float))
    return (v / 2.0) * (gamma_p * np.exp(-bphi) + gamma_m * np.exp(bphi)) \
        + (1.0 - (v / 2.0) * (gamma_p + gamma_m)) * S


def number_densities(phi, E, n_b, v):
    """eq 2: n_+- = n_b e^{-+ b e0 phi} / D. Returns (n_plus, n_minus)."""
    bphi = _bphi(phi)
    D = denominator_D(phi, E, v)
    return n_b * np.exp(-bphi) / D, n_b * np.exp(bphi) / D


def n_water(phi, E, v):
    """eq 4 (E1 fix D_4 == D): n_w = n_w^b * [sinh(bpE)/(bpE)] / D."""
    S = sinhc(beta * P_DIP * np.asarray(E, dtype=float))
    return n_w_b * S / denominator_D(phi, E, v)


def eps_eff(phi, E, v):
    """eq 3: eps_eff = eps_opt + (n_w p / E) L(bpE)
            = eps_opt + n_w beta p^2 Lc(bpE)   (Lc = L/u, smooth at E = 0).
    Low-field limit eps_eff(0,0) = eps_S exactly."""
    u = beta * P_DIP * np.asarray(E, dtype=float)
    return eps_opt + n_water(phi, E, v) * beta * P_DIP**2 * langevin_Lc(u)


# ── pb1d.py (1-D modified PB solver + analytic helpers; eqs 1,5,6,10,11) ──
def make_grid(lam_D, n=257, z_max_over_lamD=25.0, stretch=7.0):
    """Nonuniform z grid [m], length n, clustered at the wall (z=0)."""
    s = np.linspace(0.0, 1.0, n)
    return z_max_over_lamD * lam_D * (np.exp(stretch * s) - 1.0) / (np.exp(stretch) - 1.0)


def _control_volumes(z):
    h = np.diff(z)
    w = np.empty(z.size)
    w[0] = h[0] / 2.0
    w[-1] = h[-1] / 2.0
    w[1:-1] = 0.5 * (h[:-1] + h[1:])
    return h, w


def _charge_density(phi, E_node, n_b, v):
    """rho = e_0 (n_+ - n_-)  [C/m^3]."""
    n_plus, n_minus = number_densities(phi, E_node, n_b, v)
    return e_0 * (n_plus - n_minus)


def _assemble(phi, z, h, n_b, v):
    """Face fluxes J [length n-1], node field E_node, charge density rho."""
    dphi = np.diff(phi)
    phi_f = 0.5 * (phi[:-1] + phi[1:])
    E_f = np.abs(dphi / h)
    eps_f = eps_eff(phi_f, E_f, v)
    J = eps_f * dphi / h
    E_node = np.empty(z.size)
    E_node[1:-1] = 0.5 * (E_f[:-1] + E_f[1:])
    E_node[0] = E_f[0]
    E_node[-1] = E_f[-1]
    rho = _charge_density(phi, E_node, n_b, v)
    return J, rho


def _residual_dirichlet(phi_int, psi_0, z, h, w, n_b, v):
    phi = np.empty(z.size)
    phi[0] = psi_0
    phi[-1] = 0.0
    phi[1:-1] = phi_int
    J, rho = _assemble(phi, z, h, n_b, v)
    # interior nodes 1..N-1:  J_{i+1/2} - J_{i-1/2} + rho_i w_i = 0
    return (J[1:] - J[:-1]) + rho[1:-1] * w[1:-1]


def solve_dirichlet(psi_0, c_b_M, n=257, z_max_over_lamD=25.0, stretch=7.0,
                    phi_guess=None):
    """Solve the diffuse layer for a fixed wall potential psi_0 [V]."""
    lam = lambda_D(c_b_M)
    z = make_grid(lam, n, z_max_over_lamD, stretch)
    h, w = _control_volumes(z)
    n_b, v = n_b_local(c_b_M), v_frac(c_b_M)
    if phi_guess is None:
        phi_guess = psi_0 * np.exp(-z / lam)
    sol = root(_residual_dirichlet, np.asarray(phi_guess)[1:-1],
               args=(psi_0, z, h, w, n_b, v), method="hybr")
    phi = np.empty(z.size)
    phi[0] = psi_0
    phi[-1] = 0.0
    phi[1:-1] = sol.x
    R = _residual_dirichlet(sol.x, psi_0, z, h, w, n_b, v)
    J, rho = _assemble(phi, z, h, n_b, v)
    res_inf = float(np.linalg.norm(R, np.inf))
    res_rel = res_inf / (float(np.max(np.abs(J))) + 1e-300)
    sigma_M = float(-np.sum(rho * w))   # sigma_M = -Q_diff (Gauss + neutrality)
    return dict(z=z, phi=phi, success=bool(sol.success), res_inf=res_inf,
                res_rel=res_rel, sigma_M=sigma_M, lam_D=lam, v=v, n_b=n_b)


def diffuse_capacitance(psi_0, c_b_M, dpsi=5e-4, **kw):
    """C_diff = d sigma_M / d psi_0  [F/m^2] by central difference (warm-started)."""
    sp_ = solve_dirichlet(psi_0 + dpsi, c_b_M, **kw)
    sm = solve_dirichlet(psi_0 - dpsi, c_b_M, **kw)
    return (sp_["sigma_M"] - sm["sigma_M"]) / (2.0 * dpsi)


def C_GC_min(c_b_M):
    """Analytic Gouy-Chapman differential-capacitance minimum eps_S/lambda_D."""
    return eps_S / lambda_D(c_b_M)


# --------------------------------------------------------------------------
# Robin (Helmholtz) boundary condition -- eq 5 -- and C_dl(E_M) -- eqs 8-9.
# E2: default 'eps_S' (as printed); 'eps_eff' is the deferred Gauss-continuity
# reading. polyc_mpb2d LOCKS bc='eps_S' (the MESH carries bc).
# --------------------------------------------------------------------------
def _residual_robin(phi_unk, E_M, E_pzc, C_H, z, h, w, n_b, v, bc):
    phi = np.empty(z.size)
    phi[:-1] = phi_unk
    phi[-1] = 0.0
    Delta = E_M - E_pzc - phi[0]
    if bc == "eps_eff":
        J_wall = -C_H * Delta
    else:                                                # "eps_S", as printed (eq 5 / eps_S)
        dphi0 = -(C_H / eps_S) * Delta
        J_wall = eps_eff(phi[0], abs(dphi0), v) * dphi0
    J, rho = _assemble(phi, z, h, n_b, v)
    R = np.empty(z.size - 1)
    R[0] = J[0] - J_wall + rho[0] * w[0]                 # half-cell at z=0
    R[1:] = (J[1:] - J[:-1]) + rho[1:-1] * w[1:-1]       # interior nodes
    return R


def _robin_root(phi_guess_full, E_M, E_pzc, C_H, z, h, w, n_b, v, bc):
    sol = root(_residual_robin, np.asarray(phi_guess_full)[:-1],
               args=(E_M, E_pzc, C_H, z, h, w, n_b, v, bc), method="hybr")
    phi = np.empty(z.size)
    phi[:-1] = sol.x
    phi[-1] = 0.0
    R = _residual_robin(sol.x, E_M, E_pzc, C_H, z, h, w, n_b, v, bc)
    return sol, phi, R


def solve_robin(E_M, E_pzc, C_H, c_b_M, bc="eps_S", n=257, z_max_over_lamD=25.0,
                stretch=7.0, phi_guess=None):
    """Solve the single-facet interface (Helmholtz + diffuse) at metal potential E_M."""
    if bc not in ("eps_S", "eps_eff"):
        raise ValueError(f"bc must be 'eps_S' or 'eps_eff', got {bc!r}")
    lam = lambda_D(c_b_M)
    z = make_grid(lam, n, z_max_over_lamD, stretch)
    h, w = _control_volumes(z)
    n_b, v = n_b_local(c_b_M), v_frac(c_b_M)
    if phi_guess is None:
        cgc = eps_S / lam                                # linear diffuse capacitance
        psi0 = (E_M - E_pzc) / (1.0 + cgc / C_H)         # GCS split of the total drop
        phi_guess = psi0 * np.exp(-z / lam)
    sol, phi, R = _robin_root(phi_guess, E_M, E_pzc, C_H, z, h, w, n_b, v, bc)
    if not sol.success:
        nstep = max(4, int(abs(E_M - E_pzc) / 0.05) + 1)
        guess = np.zeros(z.size)                         # phi == 0 solves eq 5 at E_pzc
        for EMi in np.linspace(E_pzc, E_M, nstep + 1)[1:]:
            sol, phi, R = _robin_root(guess, EMi, E_pzc, C_H, z, h, w, n_b, v, bc)
            guess = phi
    J, rho = _assemble(phi, z, h, n_b, v)
    res_inf = float(np.linalg.norm(R, np.inf))
    res_rel = res_inf / (float(np.max(np.abs(J))) + 1e-300)
    return dict(z=z, phi=phi, success=bool(sol.success), res_inf=res_inf,
                res_rel=res_rel, q_free=float(-np.sum(rho * w)), phi_0=float(phi[0]),
                lam_D=lam, v=v, n_b=n_b)


def C_dl_curve(E_M_arr, E_pzc, C_H, c_b_M, bc="eps_S", **kw):
    """Sweep E_M with continuation (warm start). Returns (q_free[E], C_dl[E])."""
    E_M_arr = np.asarray(E_M_arr, dtype=float)
    q = np.empty(E_M_arr.size)
    phi_prev = None
    for k, EM in enumerate(E_M_arr):
        s = solve_robin(EM, E_pzc, C_H, c_b_M, bc=bc, phi_guess=phi_prev, **kw)
        q[k] = s["q_free"]
        phi_prev = s["phi"]
    return q, np.gradient(q, E_M_arr)


def C_dl_GCS_series(C_H, c_b_M):
    """GCS series capacitance at E_pzc (eq 11): (1/C_H + lambda_D/eps_S)^-1 [F/m^2]."""
    return 1.0 / (1.0 / C_H + lambda_D(c_b_M) / eps_S)


# ── pb2d.py (2-D two-facet sparse-Newton solver — the core; eqs 1-9) ──
_SPARSITY_CACHE = {}


def facet_columns(y, L, x, E_pzc1, E_pzc2, C_H1, C_H2):
    """Per-column facet PZC and Helmholtz capacitance (facet 1 is y < x*L)."""
    f1 = y < x * L
    return np.where(f1, E_pzc1, E_pzc2), np.where(f1, C_H1, C_H2)


def make_grid_2d(c_b_M, L, Ny, Nz, z_max_over_lamD=25.0, stretch=7.0):
    lam = lambda_D(c_b_M)
    y = np.linspace(0.0, L, Ny, endpoint=False)        # periodic: y[Ny] == y[0] + L
    z = make_grid(lam, Nz, z_max_over_lamD, stretch)
    return y, z, lam


def _node_fields(phi, hy, z):
    """Central node-field components Ey, Ez [V/m] on the full (Ny, Nz) grid."""
    Ey = (np.roll(phi, -1, axis=0) - np.roll(phi, 1, axis=0)) / (2.0 * hy)
    Ez = np.empty_like(phi)
    Ez[:, 1:-1] = (phi[:, 2:] - phi[:, :-2]) / (z[2:] - z[:-2])
    Ez[:, 0] = (phi[:, 1] - phi[:, 0]) / (z[1] - z[0])
    Ez[:, -1] = (phi[:, -1] - phi[:, -2]) / (z[-1] - z[-2])
    return Ey, Ez


def _residual_2d(phi_unk, y, z, hy, hz, wz, n_b, v, E_M, E_pzc_col, C_H_col, Ny, Nz,
                 bc="eps_S"):
    phi = np.empty((Ny, Nz))
    phi[:, :-1] = phi_unk.reshape(Ny, Nz - 1)
    phi[:, -1] = 0.0
    Ey_n, Ez_n = _node_fields(phi, hy, z)

    # z-faces (between k, k+1), k = 0..Nz-2
    dphi_z = phi[:, 1:] - phi[:, :-1]
    Ez_zf = dphi_z / hz
    Ey_zf = 0.5 * (Ey_n[:, :-1] + Ey_n[:, 1:])
    epsZ = eps_eff(0.5 * (phi[:, :-1] + phi[:, 1:]), np.hypot(Ez_zf, Ey_zf), v)
    Fz = epsZ * dphi_z / hz

    # y-faces (between j, j+1, periodic), all k
    dphi_y = np.roll(phi, -1, axis=0) - phi
    Ez_yf = 0.5 * (Ez_n + np.roll(Ez_n, -1, axis=0))
    epsY = eps_eff(0.5 * (phi + np.roll(phi, -1, axis=0)),
                   np.hypot(dphi_y / hy, Ez_yf), v)
    Fy = epsY * dphi_y / hy

    # wall (Robin, eq 5) flux per column at k=0; E2 reading selected by bc
    Delta = E_M - E_pzc_col - phi[:, 0]
    if bc == "eps_eff":
        J_wall = -C_H_col * Delta              # Gauss continuity (eps_eff(0) cancels)
    else:                                      # "eps_S", as printed
        dphi0 = -(C_H_col / eps_S) * Delta
        J_wall = eps_eff(phi[:, 0], np.hypot(dphi0, Ey_n[:, 0]), v) * dphi0

    # charge density at nodes
    npl, nmi = number_densities(phi, np.hypot(Ey_n, Ez_n), n_b, v)
    rho = e_0 * (npl - nmi)

    # FV divergence over each CV (Ny, Nz-1): k = 0..Nz-2
    Fz_lower = np.empty((Ny, Nz - 1))
    Fz_lower[:, 0] = J_wall
    Fz_lower[:, 1:] = Fz[:, :-1]
    z_div = (Fz - Fz_lower) * hy
    Fy_k = Fy[:, :-1]
    y_div = (Fy_k - np.roll(Fy_k, 1, axis=0)) * wz[:-1]
    src = rho[:, :-1] * hy * wz[:-1]
    return (z_div + y_div + src).ravel()


def _sparsity_2d(Ny, Nz):
    """Jacobian sparsity for the (Ny, Nz-1) unknown grid."""
    key = (Ny, Nz)
    if key not in _SPARSITY_CACHE:
        nk = Nz - 1
        rows, cols = [], []
        for j in range(Ny):
            for k in range(nk):
                n = j * nk + k
                for dj in (-1, 0, 1):
                    jj = (j + dj) % Ny
                    for dk in (-1, 0, 1):
                        kk = k + dk
                        if 0 <= kk < nk:
                            rows.append(n)
                            cols.append(jj * nk + kk)
        N = Ny * nk
        _SPARSITY_CACHE[key] = sp.csr_matrix(
            (np.ones(len(rows)), (rows, cols)), shape=(N, N))
    return _SPARSITY_CACHE[key]


def _newton_2d(fun, x0, pattern, maxit=60):
    """Damped sparse Newton iterated to the residual FLOOR (stall)."""
    x = np.array(x0, dtype=float)
    R = fun(x)
    nrm = float(np.linalg.norm(R, np.inf))
    for _ in range(maxit):
        if nrm == 0.0:
            break
        J = approx_derivative(fun, x, method="2-point", sparsity=pattern)
        dx = spsolve(sp.csc_matrix(J), -R)
        alpha = 1.0
        while True:
            xn = x + alpha * dx
            Rn = fun(xn)
            nn = float(np.linalg.norm(Rn, np.inf))
            if nn < nrm or alpha < 1e-12:
                break
            alpha *= 0.5
        x, R = xn, Rn
        if nn >= 0.9 * nrm:              # cannot reduce further -> at the floor
            nrm = nn
            break
        nrm = nn
    return x, nrm


def solve_2d(E_M, c_b_M, L, x, E_pzc1, E_pzc2, C_H1, C_H2, Ny=24, Nz=48,
             z_max_over_lamD=25.0, stretch=7.0, method="newton", phi_guess=None,
             bc="eps_S"):
    """Solve the 2-D two-facet interface at metal potential E_M. Returns a dict
    with y, z, phi (Ny,Nz), success, res_inf, res_rel, q_free (per electrode area,
    eq 8), phi_HP (= phi[:,0], the HP profile), lam_D, v, E_pzc_col."""
    y, z, lam = make_grid_2d(c_b_M, L, Ny, Nz, z_max_over_lamD, stretch)
    hy = L / Ny
    hz = np.diff(z)
    _, wz = _control_volumes(z)
    n_b, v = n_b_local(c_b_M), v_frac(c_b_M)
    E_pzc_col, C_H_col = facet_columns(y, L, x, E_pzc1, E_pzc2, C_H1, C_H2)

    def _flux_scale(phi):
        # order-of-magnitude scale of the FV residual terms (constant-eps flux)
        return float(np.max(np.abs(eps_S * (phi[:, 1:] - phi[:, :-1]) / hz))) * hy + 1e-300

    def _res_rel(phi, epcol, EM):
        R = _residual_2d(phi[:, :-1].ravel(), y, z, hy, hz, wz, n_b, v, EM,
                         epcol, C_H_col, Ny, Nz, bc)
        return float(np.linalg.norm(R, np.inf)) / _flux_scale(phi)

    def _once(EM, epcol, guess):
        a = (y, z, hy, hz, wz, n_b, v, EM, epcol, C_H_col, Ny, Nz, bc)
        x0 = np.asarray(guess)[:, :-1].ravel()   # exclude the Dirichlet bulk column
        if method == "newton":
            xx, _ = _newton_2d(lambda u: _residual_2d(u, *a), x0, _sparsity_2d(Ny, Nz))
        else:
            xx = root(_residual_2d, x0, args=a, method=method).x
        phi = np.empty((Ny, Nz))
        phi[:, :-1] = xx.reshape(Ny, Nz - 1)
        phi[:, -1] = 0.0
        return phi

    if phi_guess is None:
        psi0 = (E_M - E_pzc_col) / (1.0 + (eps_S / lam) / C_H_col)
        phi_guess = psi0[:, None] * np.exp(-z[None, :] / lam)
    phi = _once(E_M, E_pzc_col, phi_guess)
    if _res_rel(phi, E_pzc_col, E_M) > 1e-7:
        # ramp E_M AND the facet-PZC contrast together from the exact trivial
        # state (E_M = PZC = Emean -> phi == 0) out to the target, warm-started.
        Emean = 0.5 * (E_pzc1 + E_pzc2)
        nstep = max(6, int((abs(E_M - Emean) + abs(E_pzc1 - E_pzc2)) / 0.05) + 1)
        guess = np.zeros((Ny, Nz))
        for t in np.linspace(0.0, 1.0, nstep + 1):
            epcol, _ = facet_columns(y, L, x, Emean + t * (E_pzc1 - Emean),
                                     Emean + t * (E_pzc2 - Emean), C_H1, C_H2)
            phi = _once(Emean + t * (E_M - Emean), epcol, guess)
            guess = phi

    # success from the flux-normalized residual at the target (config-independent).
    res_rel = _res_rel(phi, E_pzc_col, E_M)
    res_inf = res_rel * _flux_scale(phi)
    npl, nmi = number_densities(phi, np.hypot(*_node_fields(phi, hy, z)), n_b, v)
    rho = e_0 * (npl - nmi)
    q_free = float(-(hy / L) * np.sum(rho * wz[None, :]))
    return dict(y=y, z=z, phi=phi, success=bool(res_rel < 1e-7),
                res_inf=res_inf, res_rel=res_rel, q_free=q_free,
                phi_HP=phi[:, 0].copy(), lam_D=lam, v=v, E_pzc_col=E_pzc_col)


def C_dl_2facet(E_M_arr, c_b_M, L, x, E_pzc1, E_pzc2, C_H1, C_H2,
                Ny=24, Nz=48, **kw):
    """Sweep E_M (warm-started) for the two-facet electrode. Returns
    (q_free[E], C_dl[E] = dq_free/dE_M) per unit electrode area (eqs 8-9)."""
    E_M_arr = np.asarray(E_M_arr, dtype=float)
    nE = E_M_arr.size
    q = np.empty(nE)

    def _solve(EM, guess):
        return solve_2d(EM, c_b_M, L, x, E_pzc1, E_pzc2, C_H1, C_H2,
                        Ny=Ny, Nz=Nz, phi_guess=guess, **kw)

    # March OUTWARD from the point nearest the mean PZC (smallest drop, easiest).
    c0 = int(np.argmin(np.abs(E_M_arr - 0.5 * (E_pzc1 + E_pzc2))))
    s = _solve(E_M_arr[c0], None)
    q[c0] = s["q_free"]
    phi_c = s["phi"]
    phi_prev = phi_c
    for k in range(c0 + 1, nE):
        s = _solve(E_M_arr[k], phi_prev)
        q[k] = s["q_free"]
        phi_prev = s["phi"]
    phi_prev = phi_c
    for k in range(c0 - 1, -1, -1):
        s = _solve(E_M_arr[k], phi_prev)
        q[k] = s["q_free"]
        phi_prev = s["phi"]
    return q, np.gradient(q, E_M_arr)


def count_minima(C_dl, prominence_frac=0.0):
    """Indices of interior local minima of C_dl(E)."""
    C = np.asarray(C_dl, dtype=float)
    rng = float(C.max() - C.min()) or 1.0
    out = []
    for i in range(1, len(C) - 1):
        if C[i] < C[i - 1] and C[i] < C[i + 1]:
            prom = min(C[:i].max() - C[i], C[i + 1:].max() - C[i])
            if prom >= prominence_frac * rng:
                out.append(i)
    return out


def minima_from_qfree(E_M_arr, q_free, n_fine=4001, prom_frac=0.02):
    """Clean C_dl(E) = dq_free/dE_M via a cubic spline of q_free(E_M), then locate
    minima on a fine grid. Returns (E_fine, C_dl_fine, [(E_min, C_min), ...])."""
    E = np.asarray(E_M_arr, dtype=float)
    cs = CubicSpline(E, np.asarray(q_free, dtype=float))
    Ef = np.linspace(float(E[0]), float(E[-1]), n_fine)
    Cf = cs(Ef, 1)                              # first derivative = C_dl
    rng = float(Cf.max() - Cf.min()) or 1.0
    peaks, _ = find_peaks(-Cf, prominence=prom_frac * rng)
    return Ef, Cf, [(float(Ef[i]), float(Cf[i])) for i in peaks]


# ── analytics.py (closed-form CONSTRAINTS §2 relations; eqs 10-13) ────
def C_GC(E, E_pzc, lam_D):
    """eq 10: C_GC(E) = (eps_S/lam_D) cosh(e_0 (E - E_pzc)/(2 k_B T))."""
    E = np.asarray(E, dtype=float)
    return (eps_S / lam_D) * np.cosh(e_0 * (E - E_pzc) / (2.0 * k_B * T))


def C_dl_GCS(C_H, C_gc):
    """eq 11: series capacitance 1/C_dl = 1/C_H + 1/C_GC."""
    return 1.0 / (1.0 / C_H + 1.0 / C_gc)


def theta_ads(E, E_ads0, c_b_Aminus):
    """eq 12 closed form: theta = sigma/(1+sigma),
    sigma = c_b_Aminus * exp(beta e_0 (E - E_ads0))."""
    E = np.asarray(E, dtype=float)
    sigma = c_b_Aminus * np.exp(beta * e_0 * (E - E_ads0))
    return sigma / (1.0 + sigma)


def dtheta_dE(E, E_ads0, c_b_Aminus):
    """d theta/dE = beta e_0 theta (1 - theta)."""
    th = theta_ads(E, E_ads0, c_b_Aminus)
    return beta * e_0 * th * (1.0 - th)


def C_ads(E, E_ads0, c_b_Aminus, theta_max, N_tot=None):
    """eq 13: C_ads = theta_max e_0 N_tot d theta/dE (positive for oxidative ads)."""
    Nt = globals()['N_tot'] if N_tot is None else N_tot
    return theta_max * e_0 * Nt * dtheta_dE(E, E_ads0, c_b_Aminus)


def C_ads_peak(theta_max, N_tot=None):
    """Closed-form peak (at theta = 1/2): C_ads_peak = theta_max e_0^2 N_tot beta/4."""
    Nt = globals()['N_tot'] if N_tot is None else N_tot
    return theta_max * e_0**2 * Nt * beta / 4.0


# ═════════════════════════════════════════════════════════════════════
# DRIVER — emit one RESULT_JSON line. (main is NEW to the skeleton; polyc src
# has no main() — its deliverables run via run_F*.py research scripts.)
# ═════════════════════════════════════════════════════════════════════
def main():
    Ny = int(MESH['Ny'])
    Nz = int(MESH['Nz'])
    zmax = float(MESH.get('z_max_over_lamD', 25.0))
    stretch = float(MESH.get('stretch', 7.0))
    bc = MESH.get('bc', 'eps_S')
    E_pzc1, E_pzc2 = CASE['E_pzc'][0], CASE['E_pzc'][1]
    C_H1, C_H2 = CASE['C_H'][0], CASE['C_H'][1]

    # ── single solve at CASE (always; gates parse RESULT_JSON) ──
    s = solve_2d(CASE['E_M'], C_B_M, CASE['L'], CASE['x'],
                 E_pzc1, E_pzc2, C_H1, C_H2,
                 Ny=Ny, Nz=Nz, z_max_over_lamD=zmax, stretch=stretch, bc=bc)
    phi_HP = np.asarray(s['phi_HP'], dtype=float)
    out = {
        'success': bool(s['success']),
        'residual_norm': float(s['res_inf']),       # solver inf-norm residual (consistent w/ ref)
        'res_rel': float(s['res_rel']),             # flux-normalized residual (the convergence metric)
        'sigma': float(s['q_free']),                # eq-8 free charge per electrode area [C/m^2]
        'q_free': float(s['q_free']),
        'phi_HP_min_V': float(phi_HP.min()),
        'phi_HP_max_V': float(phi_HP.max()),
        'lam_D': float(s['lam_D']),
        'L_over_lamD': float(CASE['L'] / s['lam_D']),
        'case': {'E_M': float(CASE['E_M']), 'E_pzc': [float(E_pzc1), float(E_pzc2)],
                 'C_H': [float(C_H1), float(C_H2)], 'x': float(CASE['x']),
                 'c_b_molm3': float(CASE['c_b']), 'c_b_M': float(C_B_M),
                 'L': float(CASE['L'])},
        'mesh': {k: (float(vv) if isinstance(vv, (int, float)) else vv)
                 for k, vv in MESH.items()},
    }

    # ── C_dl(E_M) curve + minima over a symmetric window about the PZC mean ──
    E_lo = min(E_pzc1, E_pzc2) - 0.5
    E_hi = max(E_pzc1, E_pzc2) + 0.5
    E = np.linspace(E_lo, E_hi, 41)
    q_curve, _ = C_dl_2facet(E, C_B_M, CASE['L'], CASE['x'],
                             E_pzc1, E_pzc2, C_H1, C_H2,
                             Ny=Ny, Nz=Nz, z_max_over_lamD=zmax, stretch=stretch, bc=bc)
    Ef, Cf, minima = minima_from_qfree(E, q_curve, prom_frac=0.04)
    out['E_M_grid'] = E.tolist()
    out['q_free_curve'] = [float(v) for v in q_curve]
    out['E_fine'] = Ef.tolist()
    out['C_dl'] = [float(v) for v in Cf]                       # SI [F/m^2]
    out['C_dl_uFcm2'] = [float(SI_to_uFcm2(v)) for v in Cf]    # display view [uF/cm^2]
    out['minima'] = [[float(em), float(cm)] for (em, cm) in minima]     # SI [(E_V, C_Fm2)]
    out['minima_uFcm2'] = [[float(em), float(SI_to_uFcm2(cm))] for (em, cm) in minima]
    out['n_minima'] = int(len(minima))
    out['C_dl_min_F_per_m2'] = float(np.min(Cf))

    # ── Parsons-Zobel slope/R^2 across c_b (eqs 10-11), as run_F4 ──
    # (1/C_GC, 1/C_dl_min) over a c_b series; drop points where >=2 minima.
    lam_ref = lambda_D(C_B_M)
    cb_series_mM = [0.1, 0.3, 1.0, 3.0, 10.0]
    xs, ys = [], []
    for cb_mM in cb_series_mM:
        cb_M = mM_to_M(cb_mM)
        qk, _ = C_dl_2facet(E, cb_M, CASE['L'], CASE['x'],
                            E_pzc1, E_pzc2, C_H1, C_H2,
                            Ny=Ny, Nz=Nz, z_max_over_lamD=zmax, stretch=stretch, bc=bc)
        Efk, Cfk, mk = minima_from_qfree(E, qk, prom_frac=0.04)
        if len(mk) >= 2:
            continue                                   # split-minimum point: drop (run_F4)
        cdl_min = float(np.min(Cfk))
        c_gc = float(C_GC(0.5 * (E_pzc1 + E_pzc2), 0.5 * (E_pzc1 + E_pzc2),
                          lambda_D(cb_M)))             # eq-10 minimum eps_S/lam_D
        xs.append(1.0 / c_gc)
        ys.append(1.0 / cdl_min)
    if len(xs) >= 2:
        xs_a = np.asarray(xs)
        ys_a = np.asarray(ys)
        slope, intercept = np.polyfit(xs_a, ys_a, 1)
        yhat = slope * xs_a + intercept
        ss_res = float(np.sum((ys_a - yhat) ** 2))
        ss_tot = float(np.sum((ys_a - ys_a.mean()) ** 2)) or 1.0
        out['pz_slope'] = float(slope)
        out['pz_intercept'] = float(intercept)
        out['pz_r2'] = float(1.0 - ss_res / ss_tot)
    else:
        out['pz_slope'] = None
        out['pz_intercept'] = None
        out['pz_r2'] = None

    # ── adsorption (gated on theta_max>0; eqs 12-13, E4 standard state) ──
    if ADS['theta_max'] > 0.0:
        c_b_Aminus = 1.0 / C_B_M                       # E4: c_b^(A-) = 1/c_b[M]
        Cads = C_ads(Ef, ADS['E_ads0'], c_b_Aminus, ADS['theta_max'])
        Ctot = Cf + Cads
        # E_min shift in meV: total-capacitance minimum vs the no-adsorption minimum.
        i_base = int(np.argmin(Cf))
        i_tot = int(np.argmin(Ctot))
        emin0 = float(Ef[i_base])
        emin = float(Ef[i_tot])
        out['adsorption_on'] = True
        out['adsorption_E_ads0'] = float(ADS['E_ads0'])
        out['adsorption_theta_max'] = float(ADS['theta_max'])
        out['C_ads_peak_uFcm2'] = float(SI_to_uFcm2(C_ads_peak(ADS['theta_max'])))
        out['adsorption_emin_base_V'] = emin0
        out['adsorption_emin_total_V'] = emin
        out['adsorption_shift_meV'] = float((emin - emin0) * 1000.0)
    else:
        out['adsorption_on'] = False
        out['adsorption_shift_meV'] = None

    # ── optional E_M sweep -> one CSV per requested L (bare relative filenames) ──
    if SWEEP['var'] == 'E_M' and SWEEP['n'] is not None and int(SWEEP['n']) >= 2:
        E_vals = np.linspace(float(SWEEP['lo']), float(SWEEP['hi']), int(SWEEP['n']))
        sweep_ok = True
        sweep_csv = []
        for L_nm in SWEEP['panel_L_nm']:
            L_m = float(L_nm) * 1e-9                    # nm -> m at the call site
            qv, _ = C_dl_2facet(E_vals, C_B_M, L_m, CASE['x'],
                                E_pzc1, E_pzc2, C_H1, C_H2,
                                Ny=Ny, Nz=Nz, z_max_over_lamD=zmax,
                                stretch=stretch, bc=bc)
            _, Cv, _ = minima_from_qfree(E_vals, qv, prom_frac=0.04)
            C_on_grid = np.gradient(qv, E_vals)        # C_dl on the sweep grid for the CSV
            fname = f'sweep_L{round(float(L_nm))}nm.csv'
            np.savetxt(fname, np.column_stack([E_vals, qv, C_on_grid]),
                       header='E_M_V,q_free_Cm2,C_dl_Fm2', delimiter=',', comments='')
            sweep_csv.append(fname)
            sweep_ok = sweep_ok and bool(np.all(np.isfinite(qv)))
        out['sweep_csv'] = sweep_csv
        out['sweep_all_converged'] = bool(sweep_ok)

    print('RESULT_JSON: ' + json.dumps(out))


if __name__ == '__main__':
    main()
