"""COMSOL model builder (MPh) — 2-D MODIFIED Poisson-Boltzmann two-facet stripe.

GENERATED by the TEMPLATE pipeline (template polyc_mpb2d v1) — do not edit by hand.
Problem: p12_booth_single

EXECUTION DEFERRED: requires a COMSOL license + MPh runtime. On this artifact
only STATIC validation is performed (AST parse, MPh API lint against the
introspected surface, parameter completeness, facet-selection count). The model
is never executed here.

Physics (full mPB, eqs 1-13 of physics.frozen.md): a 2-D modified
Poisson-Boltzmann equation with asymmetric-ion steric crowding (Bikerman
denominator D, eq 2), Langevin solvent polarization with a field-dependent
(Booth) effective permittivity eps_eff(|grad phi|) (eq 3) and position-dependent
water density n_w (eq 4, D4==D per erratum E1), facet-resolved Robin / Helmholtz
boundary conditions at z=0 (eq 5, LOCKED prefactor bc='eps_S', erratum E2),
Dirichlet phi=0 at z=Zmax (eq 6), y-periodicity (eq 7), and an opt-in Langmuir
specific-adsorption capacitance C_ads (eqs 12-13, active only when theta_max>0).

The weak form is assembled as a GeneralFormPDE for the dimensional surface
potential phi (units V): conservative flux Ga = -eps_eff*grad(phi), source
f = -e_0*(n_plus - n_minus), with eps_eff, n_plus, n_minus, the steric
denominator D and the Langevin term carried as named COMSOL variable
expressions so the PDE feature references them by name. All structural model
building is routed through `model = pymodel.java` (deep COMSOL/Java chains are
not lint-inspected); only `client.*` / `pymodel.*` calls hit the MPh surface.
"""

import mph


def build():
    client = mph.start(cores=1)
    pymodel = client.create('polyc_mpb2d')
    model = pymodel.java

    # ── parameters: every FILLED slot appears here (units in COMSOL syntax) ──
    # core (required) slots
    pymodel.parameter('E_M',     '-0.15 [V]')
    pymodel.parameter('E_pzc_1', '0.0 [V]')
    pymodel.parameter('E_pzc_2', '0.0 [V]')
    pymodel.parameter('c_b',     '0.1 [mol/m^3]')
    pymodel.parameter('L',       '1e-08 [m]')
    # optional slots (always resolved from defaults; appear unconditionally)
    pymodel.parameter('C_H_1',   '0.25 [F/m^2]')
    pymodel.parameter('C_H_2',   '0.25 [F/m^2]')
    pymodel.parameter('x_frac',  '0.5')
    pymodel.parameter('E_ads0',  '0.45 [V]')
    pymodel.parameter('theta_max', '0.0')

    # ── frozen constants (Table S1 SI; polyc T=298 K) as COMSOL expressions ──
    pymodel.parameter('e_0',     '1.6021e-19 [C]')
    pymodel.parameter('k_B',     '1.381e-23 [J/K]')
    pymodel.parameter('T0',      '298.0 [K]')
    pymodel.parameter('N_A',     '6.02e23 [1/mol]')
    pymodel.parameter('eps_0',   '8.85e-12 [F/m]')
    pymodel.parameter('eps_opt', '1.62e-11 [F/m]')      # = 1.8 * eps_0  (optical)
    pymodel.parameter('eps_HP',  '2.655e-10 [F/m]')     # = 30  * eps_0  (metal<->HP)
    pymodel.parameter('eps_S',   '6.94725e-10 [F/m]')   # = 78.5* eps_0  (bulk water)
    pymodel.parameter('d_t',     '3.1e-10 [m]')         # lattice size
    pymodel.parameter('gamma_p', '3.0')                 # ion-size factor gamma_+
    pymodel.parameter('gamma_m', '3.0')                 # ion-size factor gamma_-
    pymodel.parameter('p_dip',   '1.58e-29 [C*m]')      # solvent dipole moment
    pymodel.parameter('N_tot',   '1.5029e19 [1/m^2]')   # metal atom areal density

    # ── derived bulk / field-physics quantities (named COMSOL expressions) ──
    pymodel.parameter('beta',    '1/(k_B*T0)')                       # 1/(J)
    pymodel.parameter('n_b',     'c_b*N_A')                          # bulk ion number density [1/m^3]
    pymodel.parameter('v_frac',  '2*d_t^3*n_b')                      # bulk ion volume fraction (eq: v=2 d_t^3 n_b)
    pymodel.parameter('n_w_b',   '1/d_t^3')                          # bulk water number density (eq-3 low-field limit -> eps_S)
    pymodel.parameter('lambda_D',
                      'sqrt(eps_S*k_B*T0/(2*e_0^2*n_b))')            # Debye length (monovalent)
    pymodel.parameter('Zmax',    '25*lambda_D')
    # Robin coupling per facet (eq 5; prefactor eps_S LOCKED, erratum E2):
    #   dphi/dz|_0 = -(1/eps_S)*C_H^i*(E_M - E_pzc^i - phi_HP)
    pymodel.parameter('nu_1',    'C_H_1/eps_S')                      # Robin slope coeff facet 1 [1/m]
    pymodel.parameter('nu_2',    'C_H_2/eps_S')                      # Robin slope coeff facet 2 [1/m]
    pymodel.parameter('Phi_1',   'E_M - E_pzc_1')                    # facet-1 Helmholtz drive [V]
    pymodel.parameter('Phi_2',   'E_M - E_pzc_2')                    # facet-2 Helmholtz drive [V]

    # ── component + geometry: two-facet stripe (y in [0,L], z in [0,Zmax]) ──
    comp = model.component().create('comp1', True)
    geom = comp.geom().create('geom1', 2)
    # facet 1 rectangle: y in [0, x_frac*L]
    r1 = geom.create('r1', 'Rectangle')
    r1.set('size', ['x_frac*L', 'Zmax'])
    r1.set('pos', ['0', '0'])
    # facet 2 rectangle: y in [x_frac*L, L]
    r2 = geom.create('r2', 'Rectangle')
    r2.set('size', ['(1-x_frac)*L', 'Zmax'])
    r2.set('pos', ['x_frac*L', '0'])
    geom.run()

    # ── boundary selections: facet 1 / facet 2 electrode edges at z=0 ──
    # EXACTLY two 'boundary_facet*' selections (static check 4).
    sel1 = comp.selection().create('boundary_facet1', 'Box')
    sel1.set('entitydim', 1)
    sel1.set('xmin', '0').set('xmax', 'x_frac*L')
    sel1.set('ymin', '0').set('ymax', '0')
    sel1.set('condition', 'inside')
    sel2 = comp.selection().create('boundary_facet2', 'Box')
    sel2.set('entitydim', 1)
    sel2.set('xmin', 'x_frac*L').set('xmax', 'L')
    sel2.set('ymin', '0').set('ymax', '0')
    sel2.set('condition', 'inside')

    # ── field-dependent material variables (the heavy mPB nonlinearities) ──
    # Defined as a Variables node so the PDE feature references them by name.
    # E = |grad phi| (regularized to avoid the E->0 removable singularity in the
    # Langevin/sinhc terms); sinhc(u)=sinh(u)/u; Langevin L(u)=coth(u)-1/u.
    var = comp.variable().create('var_mpb')
    var.set('Efield',  'sqrt(phix^2 + phiz^2) + 1e-30 [V/m]')        # |grad phi|, regularized
    var.set('u_arg',   'beta*p_dip*Efield')                          # u = beta p E (dimensionless)
    var.set('sinhc',   'sinh(u_arg)/u_arg')                          # sinh(u)/u (eq 2/4 last term, eq 3 numerator)
    var.set('lang_L',  '1/tanh(u_arg) - 1/u_arg')                    # Langevin L(u) = coth(u) - 1/u (eq 3)
    # steric / Bikerman denominator D (eq 2): asymmetric-ion + solvent terms
    var.set('expo_p',  'exp(-beta*e_0*phi)')                         # e^(-beta e_0 phi)  (cation Boltzmann)
    var.set('expo_m',  'exp(+beta*e_0*phi)')                         # e^(+beta e_0 phi)  (anion Boltzmann)
    var.set('D_steric',
            '(v_frac/2)*(gamma_p*expo_p + gamma_m*expo_m)'
            ' + (1 - (v_frac/2)*(gamma_p + gamma_m))*sinhc')         # eq 2 denominator D
    # number densities (eq 2): n_± = n_b e^(∓ beta e_0 phi)/D
    var.set('n_plus',  'n_b*expo_p/D_steric')                        # cation density [1/m^3]
    var.set('n_minus', 'n_b*expo_m/D_steric')                        # anion  density [1/m^3]
    # position-dependent water density (eq 4; D4 == D per erratum E1)
    var.set('n_w',     'n_w_b*sinhc/D_steric')                       # local water density [1/m^3]
    # field-dependent (Booth) effective permittivity (eq 3)
    var.set('eps_eff', 'eps_opt + (n_w*p_dip/Efield)*lang_L')        # eps_eff(|grad phi|) [F/m]

    # ── physics: GeneralFormPDE for dimensional phi (the mPB weak form) ──
    # eq 1: div(eps_eff grad phi) = -e_0 (n_+ - n_-)
    #   conservative flux  Ga = -eps_eff*grad(phi)  (Ga = {Ga_x, Ga_y})
    #   source             f  = -e_0*(n_plus - n_minus)
    #   damping/mass       da = 0  (steady state)
    pde = comp.physics().create('g', 'GeneralFormPDE', 'geom1')
    pde.field('dimensionless').field('phi')         # dep var phi (potential, V)
    pde.prop('Units').set('DependentVariableQuantity', 'electricpotential')
    pde.prop('Units').set('SourceTermQuantity', 'chargevolumedensity')
    pde.feature('gfeq1').set('Ga', ['-eps_eff*phix', '-eps_eff*phiz'])
    pde.feature('gfeq1').set('f',  '-e_0*(n_plus - n_minus)')
    pde.feature('gfeq1').set('da', '0')

    # Robin (Helmholtz) BC per facet at z=0 (eq 5). For GeneralFormPDE the
    # inward flux is -n.Ga = g - q*phi; mapping the target
    #   dphi/dz|_0 = -nu_i*(phi - Phi_i)
    # through Ga=-eps_eff*grad(phi) gives g = eps_eff*nu_i*Phi_i, q = eps_eff*nu_i.
    fl1 = pde.create('flux1', 'FluxBoundary', 1)
    fl1.selection().named('boundary_facet1')
    fl1.set('g', 'eps_eff*nu_1*Phi_1')
    fl1.set('q', 'eps_eff*nu_1')
    fl2 = pde.create('flux2', 'FluxBoundary', 1)
    fl2.selection().named('boundary_facet2')
    fl2.set('g', 'eps_eff*nu_2*Phi_2')
    fl2.set('q', 'eps_eff*nu_2')

    # Dirichlet phi=0 at z=Zmax (eq 6, bulk reference)
    dir1 = pde.create('dir1', 'DirichletBoundary', 1)
    dir1.selection().set(4)   # top edge index after geom union (resolved at runtime)
    dir1.set('r', '0 [V]')

    # Periodic in y (eq 7): phi(y=0) = phi(y=L)
    per1 = pde.create('pc1', 'PeriodicCondition', 1)
    per1.set('PeriodicType', 'Continuity')


    # ── mesh (tier 'diagnostic': mapped, refined toward z=0) ──
    mesh = comp.mesh().create('mesh1')
    mp = mesh.create('map1', 'Map')
    dis = mp.create('dis1', 'Distribution')
    dis.set('numelem', 48)
    dis.set('type', 'predefined')
    dis.set('elemratio', 7)
    dis.set('symmetric', False)
    dis2 = mp.create('dis2', 'Distribution')
    dis2.set('numelem', 24)
    mesh.run()

    # ── study: stationary ──
    std = model.study().create('std1')
    std.create('stat', 'Stationary')


    # ── exports: free charge per facet via Gauss closure (eq 8) ──
    # q_free = (1/L) ∫_0^L eps_eff(z=0) dphi/dz|_0 dy ; C_dl = dq_free/dE_M (eq 9).
    table = model.result().table().create('tbl1', 'Table')
    gev = model.result().numerical().create('gev1', 'EvalGlobal')
    gev.set('table', 'tbl1')
    gev.set('expr', ['E_M'])
    model.result().export().create('exp1', 'Table')
    model.result().export('exp1').set('table', 'tbl1')
    model.result().export('exp1').set('filename', 'comsol_sweep.csv')

    # ── solve the stationary study so the saved .mph is a SOLVED model ──
    # Best-effort: a solve/convergence failure must NOT block delivery of the .mph,
    # so it is caught and the model is still saved (built, unsolved) below. A licensed
    # COMSOL run validates convergence and the export expression above (eqs 8-9).
    try:
        pymodel.solve('std1')
        model.result().export('exp1').run()
    except Exception as exc:
        print(f'COMSOL solve/export deferred (needs a licensed run): {exc}')

    pymodel.save('polyc_mpb2d_p12_booth_single.mph')
    return pymodel


if __name__ == '__main__':
    build()
